# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: 'Python_Tests'
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'

    - script: python -m pip install --upgrade pip setuptools wheel
      displayName: 'Install tools'


    - script: python -m pip install --upgrade tox
      displayName: 'Install Tox'

    - script: tox -e py
      displayName: 'Run Tox'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-output.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'

    - task: PublishCodeCoverageResults@1
      inputs:
        codecoveragetool: Cobertura
        summaryFileLocation: '**/coverage.xml'

- stage: 'getPythonPath_tests'
  jobs:
  - job: TestonLinux
    pool:
      vmImage: 'ubuntu-latest'
      demands: npm

    steps:
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: buildAndReleaseTask
        verbose: false

    - task: Npm@1
      displayName: 'mocha tests'
      inputs:
        command: 'custom'
        workingDir: buildAndReleaseTask
        customCommand: 'test'
        verbose: false

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/ResultsFile.xml'
        testRunTitle: 'Publish test results for getPythonPath.ts on linux'

  - job: TestonWindows
    pool:
      vmImage: 'windows-latest'
      demands: npm

    steps:
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: buildAndReleaseTask
        verbose: false

    - task: Npm@1
      displayName: 'mocha tests'
      inputs:
        command: 'custom'
        workingDir: buildAndReleaseTask
        customCommand: 'test'
        verbose: false

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/ResultsFile.xml'
        testRunTitle: 'Publish test results for getPythonPath.ts on Windows'

  - job: TestonOSX
    pool:
      vmImage: 'macos-latest'
      demands: npm

    steps:
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: buildAndReleaseTask
        verbose: false

    - task: Npm@1
      displayName: 'mocha tests'
      inputs:
        command: 'custom'
        workingDir: buildAndReleaseTask
        customCommand: 'test'
        verbose: false

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/ResultsFile.xml'
        testRunTitle: 'Publish test results for getPythonPath.ts on MacOS'
