# Test plugin on build pipeline

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TlsTestGate@1
  displayName: 'github.com SSL/TLS Test Gate'
  inputs:
    baseURL: github.com
    port: 443
    failBuild: false



