# Example yaml pipeline

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TlsTestGate@1
  displayName: 'github.com SSL/TLS Test Gate'
  inputs:
   baseURL: 'github.com'
   dnsserver: 8.8.8.8
   port: 443
   failBuild: false
