name: TlsTestGate-NodeTests
env:
  NODE_VERSION: 16
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: buildAndReleaseTask/package-lock.json
      - name: Install packages
        run: npm ci
        working-directory: buildAndReleaseTask
      - name: Run lint
        run: npm run lint
        working-directory: buildAndReleaseTask
