name: TlsTestGate-Test
env:
  NODE_VERSION: 16
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: buildAndReleaseTask/package-lock.json
      - name: Install packages
        run: npm ci
        working-directory: buildAndReleaseTask
      - name: Run lint
        run: npm run lint
        working-directory: buildAndReleaseTask
