name: "Test Report"
on:
  workflow_run:
    workflows: ["TlsTestGate-Test"]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results # artifact name
          name: JEST Tests
          path: "*.xml"
          reporter: jest-junit # Format of test results
